/*
 * Ecology Coach
 * Copyright © 2026 Dr. Tahir Ali
 * All rights reserved. See LICENSE.
 */

import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.8";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const LANGUAGE="de";
const instructions=LANGUAGE==="de"?`Du bist Ecology Coach, ein wissenschaftlich präziser Tutor für universitäre Ökologie. Antworte auf Deutsch. Unterstütze Lernende auf unterschiedlichen Niveaus. Prüfe fachliche Richtigkeit, Argumentation, Statistik, wissenschaftliches Schreiben und Fachsprache. Erfinde keine Kursdaten. Markiere Unsicherheit. Bei daily_lesson liefere eine reichhaltige strukturierte Lektion mit Lernziel, Schlüsselkonzepten, typischen Fehlern, zwei Fachbegriffen, Reflexionsfrage, Mini-Übung und empfohlenem Modul. Gib ausschließlich gültiges JSON.`:`You are Ecology Coach, a scientifically rigorous university ecology tutor. Respond in English. Support learners at different levels. Evaluate disciplinary accuracy, reasoning, statistics, scientific writing and technical communication. Never invent course data. Mark uncertainty. For daily_lesson provide a rich structured lesson with a learning objective, key concepts, common mistakes, two technical terms, a reflection question, a mini exercise and a recommended module. Return valid JSON only.`;
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const auth=req.headers.get("Authorization")??"";const jwt=auth.replace(/^Bearer\s+/i,"");if(!jwt)return response({error:"Authentication required"},401);const url=Deno.env.get("SUPABASE_URL")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,gemini=Deno.env.get("GEMINI_API_KEY")!;const admin=createClient(url,service,{auth:{persistSession:false}});const{data:userData,error:userError}=await admin.auth.getUser(jwt);if(userError||!userData.user)return response({error:"Invalid session"},401);const user=userData.user;const body=await req.json();const mode=String(body.mode??"conversation"),message=String(body.message??"").trim();if(!message)return response({error:"Message required"},400);const{data:settings}=await admin.from("user_ai_settings").select("daily_limit,max_message_chars").eq("user_id",user.id).maybeSingle();const limit=settings?.daily_limit??30,maxChars=settings?.max_message_chars??4000;if(message.length>maxChars)return response({error:`Message exceeds ${maxChars} characters`},413);const{data:qrows,error:qerr}=await admin.rpc("consume_ai_quota",{p_user_id:user.id,p_daily_limit:limit});if(qerr)throw qerr;const quota=qrows?.[0];if(!quota?.allowed)return response({error:"Daily AI quota reached",usage:{used:limit,limit,remaining:0}},429);
const prompt=JSON.stringify({mode,message,context:body.context??{},history:Array.isArray(body.history)?body.history.slice(-10):[]});const model=Deno.env.get("GEMINI_MODEL")||"gemini-3.1-flash-lite";const gr=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${gemini}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({systemInstruction:{parts:[{text:instructions}]},contents:[{role:"user",parts:[{text:prompt}]}],generationConfig:{responseMimeType:"application/json",responseSchema:{type:"OBJECT",properties:{reply:{type:"STRING"},corrections:{type:"ARRAY",items:{type:"STRING"}},vocabulary:{type:"ARRAY",items:{type:"OBJECT",properties:{term:{type:"STRING"},meaning:{type:"STRING"}},required:["term","meaning"]}},scores:{type:"OBJECT"},nextQuestion:{type:"STRING"},lesson:{type:"OBJECT",properties:{title:{type:"STRING"},learningObjective:{type:"STRING"},keyConcepts:{type:"ARRAY",items:{type:"STRING"}},commonMistakes:{type:"ARRAY",items:{type:"STRING"}},technicalTerms:{type:"ARRAY",items:{type:"OBJECT",properties:{term:{type:"STRING"},meaning:{type:"STRING"}},required:["term","meaning"]}},reflectionQuestion:{type:"STRING"},miniExercise:{type:"STRING"},recommendedModule:{type:"STRING"},estimatedMinutes:{type:"NUMBER"}}}},required:["reply","corrections","vocabulary","scores","nextQuestion"]}}})});if(!gr.ok)throw new Error(`Gemini ${gr.status}: ${await gr.text()}`);const gd=await gr.json();const txt=gd?.candidates?.[0]?.content?.parts?.map((p:any)=>p.text??"").join("")??"";const parsed=JSON.parse(txt);return response({...parsed,usage:{used:quota.request_count,limit:quota.daily_limit,remaining:quota.remaining}});}catch(e){console.error(e);return response({error:e instanceof Error?e.message:String(e)},400);}});
