/*
 * Ecology Coach
 * Copyright © 2026 Dr. Tahir Ali
 * All rights reserved. See LICENSE.
 */

begin;

-- Replace any earlier draft records for these five lecture-grounded lessons.
delete from public.lesson_questions
where lesson_id in (
  'lecture-population-ecology',
  'lecture-evolution-popgen',
  'lecture-local-adaptation',
  'lecture-climate-biomes',
  'lecture-ecophysiology'
);

delete from public.lesson_content
where lesson_id in (
  'lecture-population-ecology',
  'lecture-evolution-popgen',
  'lecture-local-adaptation',
  'lecture-climate-biomes',
  'lecture-ecophysiology'
);

insert into public.lesson_content
(lesson_id,title,learning_objective,summary,key_concepts,example,common_mistakes,vocabulary,version,active)
values
(
 'lecture-population-ecology',
 'Populationsökologie: Struktur, Demographie und Wachstum',
 'Nach 55 Minuten können Lernende Populationen räumlich und demographisch charakterisieren, Wachstumsraten berechnen, exponentielle und logistische Modelle vergleichen und Abweichungen biologisch erklären.',
 'Eine Population wird über Abundanz, Dichte, Dispersion, Altersstruktur sowie Zu- und Abwanderung beschrieben. Exponentielles Wachstum setzt konstante Bedingungen und unbegrenzte Ressourcen voraus. Das logistische Modell ergänzt eine dichteabhängige Begrenzung durch die Tragfähigkeit K. Verzögerte Reaktionen, Allee-Effekte, schwankende Umweltbedingungen und Lebenszyklus-Trade-offs erklären, warum reale Populationen von einfachen Kurven abweichen.',
 '[{"term":"Population als ökologische Einheit","definition":"Populationen sind die Ebene, auf der Geburten, Todesfälle, Immigration, Emigration, Konkurrenz und Selektion gemeinsam die zeitliche Dynamik bestimmen."},{"term":"Dispersion","definition":"Regelmäßige, zufällige oder aggregierte räumliche Verteilung; das Muster kann Konkurrenz, positive Nachbarschaftseffekte, Ressourcenheterogenität oder begrenzte Ausbreitung widerspiegeln."},{"term":"Demographische Bilanz","definition":"Änderung der Populationsgröße durch Natalität und Immigration minus Mortalität und Emigration."},{"term":"Exponentielles Wachstum","definition":"dN/dt = rN und N(t)=N0 e^(rt); geeignet für kurze Phasen unter annähernd unbegrenzten Bedingungen."},{"term":"Logistisches Wachstum","definition":"dN/dt = rN(1-N/K); die Pro-Kopf-Wachstumsrate sinkt mit zunehmender Dichte."},{"term":"Lebensstrategien und Trade-offs","definition":"Investitionen in Wachstum, Überleben und Reproduktion können nicht gleichzeitig maximiert werden; r/K- und CSR-Konzepte sind heuristische Rahmen, keine starren Kategorien."}]'::jsonb,
 'Eine Pflanzenpopulation startet mit N0 = 200 Individuen und r = 0,25 pro Jahr. Unter exponentiellen Annahmen gilt N(4)=200·e^(1) ≈ 544. Ein solches Ergebnis ist nur dann biologisch plausibel, wenn Ressourcenbegrenzung und Dichteabhängigkeit während dieses Zeitraums gering bleiben. Bei K = 600 würde die logistische Kurve bereits deutlich abflachen.',
 '["Abundanz, Dichte und Dispersion als Synonyme behandeln.","Eine aggregierte Verteilung automatisch als positive Interaktion interpretieren, ohne Ressourcenheterogenität oder begrenzte Samenverbreitung zu prüfen.","K als unveränderliche Arteigenschaft behandeln; tatsächlich hängt K von Umwelt, Raum, Ressourcen und Zeit ab.","Aus einem positiven r unmittelbar eine langfristig ungefährdete Population ableiten.","Ramets modularer Pflanzen ohne Prüfung als genetisch unabhängige Individuen zählen."]'::jsonb,
 '[{"term":"Abundanz","meaning":"Gesamtzahl der Individuen einer Population."},{"term":"Individuendichte","meaning":"Individuenzahl pro Flächen- oder Volumeneinheit."},{"term":"Kohorte","meaning":"Gruppe von Individuen vergleichbaren Alters oder Entwicklungsstadiums."},{"term":"intrinsische Wachstumsrate r","meaning":"Netto-Pro-Kopf-Wachstumsrate unter den betrachteten Bedingungen."},{"term":"Tragfähigkeit K","meaning":"Unter gegebenen Bedingungen langfristig unterstützbare Populationsgröße."},{"term":"Allee-Effekt","meaning":"Reduzierte Pro-Kopf-Fitness oder Wachstumsrate bei sehr geringer Populationsdichte."}]'::jsonb,
 1,true
),
(
 'lecture-evolution-popgen',
 'Evolution in Populationen: Mutation, Drift und Selektion',
 'Nach 60 Minuten können Lernende Hardy-Weinberg als Nullmodell verwenden, Allel- und Genotypfrequenzen berechnen, Drift populationsgrößenabhängig erklären und Selektion von zufälliger Änderung unterscheiden.',
 'Mutation erzeugt neue Allele; Evolution liegt vor, wenn sich Allelfrequenzen über Generationen ändern. Das Hardy-Weinberg-Prinzip beschreibt erwartete Genotypfrequenzen p², 2pq und q² unter idealisierten Annahmen. Endliche Populationen verletzen die Annahme unendlicher Größe: zufälliges Sampling von Gameten erzeugt Drift, besonders stark bei kleinem N. Selektion wirkt systematisch über Fitnessunterschiede, während Drift Richtung und Stärke zufällig verändert. Beide Prozesse wirken gleichzeitig.',
 '[{"term":"Mutation als Ursprung neuer Variation","definition":"Eine neue Mutation beginnt in einer diploiden Population mit N Individuen typischerweise bei Frequenz 1/(2N)."},{"term":"Hardy-Weinberg-Nullmodell","definition":"Unter Panmixie und ohne Mutation, Migration, Selektion oder Drift werden p², 2pq und q² erwartet; Abweichung diagnostiziert, erklärt aber noch nicht die Ursache."},{"term":"Genetische Drift","definition":"Zufällige Veränderung von Allelfrequenzen durch endliches Sampling; stärker und schneller in kleinen Populationen."},{"term":"Fixierung und Verlust","definition":"Unter reiner Drift ist die Fixierungswahrscheinlichkeit eines neutralen Allels gleich seiner aktuellen Frequenz."},{"term":"Selektion","definition":"Nichtzufällige Änderung aufgrund systematischer Fitnessunterschiede zwischen Genotypen oder Phänotypen."},{"term":"Drift-Selektion-Balance","definition":"Ob Selektion eine Variante zuverlässig lenkt, hängt von Effektstärke, Dominanz, Populationsgröße und stochastischer Variation ab."}]'::jsonb,
 'Bei p=0,3 und q=0,7 erwartet Hardy-Weinberg AA=0,09, Aa=0,42 und aa=0,49. In einer kleinen Population können beobachtete Frequenzen in der nächsten Generation allein durch Sampling abweichen. Eine einzelne Abweichung beweist daher weder Selektion noch Nicht-Panmixie; Replikation, zeitliche Daten und biologische Evidenz sind erforderlich.',
 '["Hardy-Weinberg als Behauptung verstehen, dass reale Populationen unverändert bleiben.","Jede Frequenzänderung als Selektion interpretieren.","Kleine Populationen als mutationsfrei ansehen; sie erhalten neue Mutationen, verlieren Variation aber schneller durch Drift.","Fixierung mit adaptiver Bedeutung gleichsetzen; neutrale oder schädliche Varianten können durch Drift fixiert werden.","Genotypfrequenzen p, q und Allelfrequenzen p², 2pq, q² verwechseln."]'::jsonb,
 '[{"term":"Allelfrequenz","meaning":"Anteil einer Allelform an allen Genkopien eines Locus."},{"term":"Panmixie","meaning":"Zufällige Paarung in Bezug auf den betrachteten Locus."},{"term":"Heterozygotie","meaning":"Wahrscheinlichkeit oder Anteil heterozygoter Genotypen; unter HWE 2pq."},{"term":"Fixierung","meaning":"Frequenz eines Allels erreicht 1."},{"term":"Verlust","meaning":"Frequenz eines Allels erreicht 0."},{"term":"effektive Populationsgröße","meaning":"Größe einer idealisierten Population, die dieselbe Driftstärke wie die reale Population zeigt."}]'::jsonb,
 1,true
),
(
 'lecture-local-adaptation',
 'Lokale Anpassung, Genfluss und Artenbildung',
 'Nach 55 Minuten können Lernende räumliche Populationsstruktur beschreiben, neutrale Struktur von lokaler Anpassung trennen, reziproke Transplantation interpretieren und den möglichen Übergang zur reproduktiven Isolation erklären.',
 'Arten bestehen häufig aus hierarchisch strukturierten Subpopulationen. Samen- und Pollenausbreitung bestimmen Genfluss, während geographische Distanz, Barrieren und kleine lokale Populationsgrößen Differenzierung fördern. Lokale Anpassung liegt vor, wenn Populationen in ihrer jeweiligen Heimat relativ höhere Fitness zeigen. Reziproke Transplantationen und Common-Garden-Experimente trennen genetische Differenzierung von Umweltplastizität. Genfluss kann Anpassung abschwächen oder adaptive Variation zuführen. Dauerhafte Divergenz kann prä- oder postzygotische Isolation und schließlich Artenbildung begünstigen.',
 '[{"term":"Hierarchische Populationsstruktur","definition":"Individuen sind in Subpopulationen, Metapopulationen und größere regionale Einheiten organisiert; Genfluss unterscheidet sich zwischen Skalen."},{"term":"Isolation by Distance","definition":"Genetische Unterschiede nehmen mit geographischer Distanz zu, wenn Genfluss überwiegend lokal stattfindet."},{"term":"Lokale Anpassung","definition":"Genetisch bedingter Heimvorteil: lokale Genotypen erreichen in ihrer Heimat relativ höhere Fitness als fremde Genotypen."},{"term":"Reziproke Transplantation","definition":"Populationen werden wechselseitig in mehreren Herkunftsumwelten getestet, um Genotyp-, Umwelt- und Interaktionseffekte auf Fitness zu trennen."},{"term":"Genfluss-Selektion-Spannung","definition":"Migration homogenisiert, divergente Selektion differenziert; das Ergebnis hängt von ihrer relativen Stärke und der räumlichen Skala ab."},{"term":"Ökologische Artenbildung","definition":"Reproduktive Isolation entwickelt sich als Folge divergenter Anpassung an unterschiedliche Umwelten."}]'::jsonb,
 'Population A stammt aus einem trockenen, Population B aus einem feuchten Standort. A übertrifft B am trockenen Standort, während B am feuchten Standort A übertrifft. Dieses Crossover-Muster unterstützt lokale Anpassung, sofern Fitness gemessen, Replikation ausreichend und maternale oder experimentelle Effekte kontrolliert wurden.',
 '["Geographische genetische Struktur automatisch als lokale Anpassung bezeichnen.","Phänotypische Unterschiede im Freiland ohne Common Garden als genetisch interpretieren.","Eine signifikante Genotyp-Umwelt-Interaktion ohne Fitnessbezug als Beweis lokaler Anpassung ansehen.","Genfluss ausschließlich als hinderlich behandeln; er kann adaptive Allele und genetische Variation zuführen.","Artenbildung als sofortige Folge jeder lokalen Differenzierung darstellen."]'::jsonb,
 '[{"term":"Genfluss","meaning":"Übertragung von Allelen zwischen Populationen durch Migration und Fortpflanzung."},{"term":"Metapopulation","meaning":"Netzwerk lokaler Populationen, die durch Kolonisation und Migration verbunden sind."},{"term":"Common Garden","meaning":"Gemeinsame kontrollierte Umwelt zur Prüfung genetisch bedingter Phänotypunterschiede."},{"term":"Heimvorteil","meaning":"Relative Fitnessüberlegenheit lokaler gegenüber fremden Genotypen in der Heimat."},{"term":"G×E-Interaktion","meaning":"Genotypen reagieren unterschiedlich auf verschiedene Umwelten."},{"term":"reproduktive Isolation","meaning":"Reduzierter Genfluss durch prä- oder postzygotische Barrieren."}]'::jsonb,
 1,true
),
(
 'lecture-climate-biomes',
 'Klima, globale Zirkulation und Biome',
 'Nach 50 Minuten können Lernende Klima, Witterung und Wetter unterscheiden, globale Zirkulationsmuster mechanistisch erklären und die Verteilung von Biomen aus Temperatur, Niederschlag und Saisonalität ableiten.',
 'Klima beschreibt langfristige statistische Muster, Witterung typische saisonale Abfolgen und Wetter kurzfristige Zustände. Erdachsenneigung und Solarstrahlung erzeugen Jahreszeiten und Breitengradienten. Globale Luftzirkulation formt äquatoriale Tiefdruck- und subtropische Hochdruckgürtel; die jahreszeitliche Verlagerung der ITCZ steuert Regen- und Trockenzeiten. Ozeanströmungen und Relief verändern regionale Muster. Terrestrische Biome entstehen aus gekoppelten Temperatur-, Niederschlags- und Saisonalitätsregimen und werden durch Vegetationsstruktur charakterisiert.',
 '[{"term":"Klimatische Skalen","definition":"Makro-, Lokal-, Bestands- und Mikroklima beschreiben unterschiedliche räumliche Ebenen ökologisch relevanter Bedingungen."},{"term":"Globale Luftzirkulation","definition":"Aufsteigende feuchte Luft an der äquatorialen Tiefdruckrinne und absinkende trockene Luft in subtropischen Hochdruckgürteln strukturieren Niederschläge."},{"term":"ITCZ und Saisonalität","definition":"Die innertropische Konvergenzzone wandert jahreszeitlich und erzeugt räumlich variable Regen- und Trockenzeiten."},{"term":"Thermohaline Zirkulation","definition":"Dichtegetriebene globale Ozeanzirkulation transportiert Wärme und beeinflusst regionale Klimate."},{"term":"Reliefeffekt","definition":"Aufsteigende Luft kühlt im Luv ab und regnet aus; im Lee erwärmt sich absinkende Luft und erzeugt Regenschatten."},{"term":"Biome","definition":"Große ökologische Zonen mit charakteristischer Vegetation, geprägt vor allem durch Makroklima und Saisonalität."}]'::jsonb,
 'Ein Standort bei 30° Breite kann trotz hoher Solarstrahlung trocken sein, weil subtropische Hochdrucksysteme absinkende, sich erwärmende Luft erzeugen. Ein Gebirge kann zusätzlich eine feuchte Luv- und trockene Leeseite schaffen. Deshalb reicht die geographische Breite allein nicht zur Vorhersage des lokalen Bioms.',
 '["Ein einzelnes Wetterereignis als Beleg für ein Klima einordnen.","Biome ausschließlich über mittlere Jahrestemperatur erklären und Niederschlagssaisonalität ignorieren.","Makroklima direkt mit dem Mikroklima unter einem Blätterdach gleichsetzen.","Ozean- und Luftzirkulation als voneinander unabhängige Systeme behandeln.","Aktuelle Vegetation ausschließlich klimatisch erklären und Boden, Störung sowie Landnutzung ausblenden."]'::jsonb,
 '[{"term":"Klima","meaning":"Langfristige statistische Verteilung meteorologischer Bedingungen."},{"term":"Witterung","meaning":"Typische Abfolge meteorologischer Erscheinungen im saisonalen Verlauf."},{"term":"Wetter","meaning":"Kurzfristiger atmosphärischer Zustand an einem Ort."},{"term":"ITCZ","meaning":"Zone konvergierender Passatwinde mit aufsteigender feuchter Luft."},{"term":"Luv und Lee","meaning":"Windexponierte Aufstiegsseite und windabgewandte Regenschattenseite eines Reliefs."},{"term":"Biome","meaning":"Großräumige Lebensgemeinschaften mit charakteristischer Vegetationsphysiognomie."}]'::jsonb,
 1,true
),
(
 'lecture-ecophysiology',
 'Pflanzenökophysiologie: Ressourcen, Stress und Plastizität',
 'Nach 60 Minuten können Lernende Ressourcenaufnahme und Umweltstress mechanistisch verknüpfen, Wasser- und Kohlenstoffökonomie erklären und Akklimatisation, Plastizität und genetische Anpassung experimentell trennen.',
 'Pflanzen benötigen Licht, CO2, Wasser sowie Makro- und Mikroelemente, müssen diese Ressourcen aber unter schwankenden Bedingungen balancieren. Bodenstruktur, Textur, Feldkapazität, Welkepunkt, pH und Ionenaustausch bestimmen die Verfügbarkeit unterirdischer Ressourcen. Stomata koppeln CO2-Aufnahme an Wasserverlust. Temperatur beeinflusst Enzymkinetik, Atmung und Photosynthese. Akklimatisation ist eine reversible Reaktion eines Individuums; phänotypische Plastizität beschreibt umweltabhängige Phänotypen eines Genotyps; Adaptation beruht auf erblichen Unterschieden über Generationen.',
 '[{"term":"Ressourcen und Bedingungen","definition":"Licht, CO2, Wasser und Nährstoffe werden verbraucht; Temperatur, Feuchte, Salzgehalt und pH verändern ihre Aufnahme und Nutzung."},{"term":"Boden-Wasser-Beziehung","definition":"Textur und Porenraum bestimmen Feldkapazität, Drainage und den permanenten Welkepunkt."},{"term":"Stomatärer Trade-off","definition":"Offene Stomata fördern CO2-Aufnahme, erhöhen aber Transpiration; Regulation balanciert Kohlenstoffgewinn und Wasserverlust."},{"term":"Temperaturleistungskurve","definition":"Physiologische Prozesse besitzen Minimum, Optimum und Maximum; kurzfristige Akklimatisation kann die Kurve verschieben."},{"term":"Phänotypische Plastizität","definition":"Ein Genotyp erzeugt abhängig von der Umwelt unterschiedliche Phänotypen."},{"term":"Adaptation","definition":"Erbliche Merkmale erhöhen Fitness in einer bestimmten Umwelt und verändern sich durch Selektion über Generationen."}]'::jsonb,
 'Zwei Herkünfte einer Pflanze unterscheiden sich im Freiland in Wuchshöhe. In einem faktoriellen Common-Garden-Experiment werden beide Herkünfte unter warmen und kalten Bedingungen kultiviert. Ein Temperatureffekt zeigt Plastizität, ein Herkunftseffekt genetische Differenzierung und eine Herkunft×Temperatur-Interaktion unterschiedliche Reaktionsnormen. Erst Fitnessmessungen in relevanten Umwelten prüfen lokale Anpassung.',
 '["Akklimatisation und Adaptation synonym verwenden.","Kleinere Pflanzen unter Trockenheit automatisch als angepasst bezeichnen, ohne Fitness zu messen.","Nährstoffkonzentration im Boden mit tatsächlicher Pflanzenverfügbarkeit gleichsetzen.","Stomataschluss nur als vorteilhaft bewerten; er spart Wasser, begrenzt aber CO2-Aufnahme und Wachstum.","Phänotypische Unterschiede zwischen Standorten ohne gemeinsames Experiment als genetisch interpretieren."]'::jsonb,
 '[{"term":"Makroelement","meaning":"In relativ großen Mengen benötigtes essentielles Element, z. B. N, P, K, Ca oder Mg."},{"term":"Feldkapazität","meaning":"Wassergehalt eines Bodens nach Abfluss des frei beweglichen Wassers."},{"term":"permanenter Welkepunkt","meaning":"Bodenwasserstatus, bei dem Pflanzen ihren Turgor dauerhaft nicht wiederherstellen können."},{"term":"Transpiration","meaning":"Wasserverlust, vor allem über Stomata."},{"term":"Akklimatisation","meaning":"Reversible physiologische Anpassung eines Individuums innerhalb seiner Lebenszeit."},{"term":"Reaktionsnorm","meaning":"Muster der Phänotypausprägung eines Genotyps über verschiedene Umwelten."}]'::jsonb,
 1,true
);

insert into public.lesson_questions
(lesson_id,question_type,prompt,options,correct_answer,explanation,points,position,active)
values
-- Population ecology
('lecture-population-ecology','multiple_choice','Welche Aussage unterscheidet Individuendichte und Dispersion korrekt?','["Dichte beschreibt die räumliche Form, Dispersion die Individuenzahl.","Dichte ist Individuenzahl pro Fläche; Dispersion beschreibt das räumliche Muster.","Beide Begriffe sind synonym.","Dispersion kann nur bei Tieren bestimmt werden."]'::jsonb,'1'::jsonb,'Dichte quantifiziert die Anzahl pro Raum; Dispersion beschreibt regelmäßig, zufällig oder aggregiert.',2,1,true),
('lecture-population-ecology','multiple_choice','Welche Annahme ist für langfristiges exponentielles Wachstum am problematischsten?','["Konstante Pro-Kopf-Wachstumsrate bei unbegrenzten Ressourcen","Vorhandensein einer Startpopulation","Messung der Zeit","Verwendung natürlicher Logarithmen"]'::jsonb,'0'::jsonb,'Konstantes r und unbegrenzte Ressourcen sind langfristig meist unrealistisch.',2,2,true),
('lecture-population-ecology','true_false','Eine positive Wachstumsrate in einem einzelnen Jahr beweist, dass die Population langfristig nicht gefährdet ist.','[true,false]'::jsonb,'false'::jsonb,'Kurzfristiges Wachstum kann durch Schwankungen, Altersstruktur oder Zuwanderung entstehen.',1,3,true),
('lecture-population-ecology','short_answer','Eine seltene Pflanze zeigt stark aggregierte Vorkommen. Nennen Sie drei alternative ökologische Erklärungen und eine Untersuchung, mit der Sie diese unterscheiden würden.',null,null,'Eine gute Antwort trennt Ressourcenheterogenität, begrenzte Ausbreitung/klonales Wachstum und biotische Interaktionen und schlägt räumliche Umweltmessungen oder genetische Identifikation vor.',4,4,true),
-- Evolution
('lecture-evolution-popgen','multiple_choice','Bei p=0,3: Welche Heterozygotenfrequenz erwartet Hardy-Weinberg?','["0,09","0,21","0,42","0,49"]'::jsonb,'2'::jsonb,'2pq = 2×0,3×0,7 = 0,42.',2,1,true),
('lecture-evolution-popgen','true_false','Unter neutraler Drift ist die Fixierungswahrscheinlichkeit eines Allels gleich seiner aktuellen Frequenz.','[true,false]'::jsonb,'true'::jsonb,'Für ein neutrales Allel entspricht die Fixierungswahrscheinlichkeit seiner aktuellen Frequenz.',1,2,true),
('lecture-evolution-popgen','multiple_choice','Warum ist Drift in kleinen Populationen stärker?','["Weil dort keine Mutation stattfindet.","Weil die Stichprobe der Gameten relativ ungenauer ist.","Weil alle Allele selektiv sind.","Weil Hardy-Weinberg nur für Pflanzen gilt."]'::jsonb,'1'::jsonb,'Endliches Sampling erzeugt größere zufällige Frequenzabweichungen bei kleinem N.',2,3,true),
('lecture-evolution-popgen','short_answer','Eine Variante steigt in 20 Generationen von 0,10 auf 0,65. Erklären Sie, warum dies allein noch keinen Selektionsnachweis darstellt und welche zusätzliche Evidenz Sie verlangen würden.',null,null,'Erwartet werden Drift, Demographie, Migration und technische Effekte als Alternativen sowie Replikation, neutrale Nullmodelle, Fitnessdaten oder parallele Veränderungen.',4,4,true),
-- local adaptation
('lecture-local-adaptation','multiple_choice','Welches Ergebnis einer reziproken Transplantation unterstützt lokale Anpassung am stärksten?','["Population A ist überall besser.","Beide Populationen sind überall gleich.","Jede Population besitzt in ihrer Heimat relative Fitnessvorteile.","Die Standorte unterscheiden sich in Temperatur."]'::jsonb,'2'::jsonb,'Lokale Anpassung wird durch einen relativen Heimvorteil in den jeweiligen Umwelten gestützt.',2,1,true),
('lecture-local-adaptation','true_false','Isolation by Distance beweist, dass Umweltselektion die genetische Struktur verursacht hat.','[true,false]'::jsonb,'false'::jsonb,'Isolation by Distance kann allein aus räumlich begrenztem neutralem Genfluss entstehen.',1,2,true),
('lecture-local-adaptation','multiple_choice','Welche Funktion kann Genfluss neben Homogenisierung haben?','["Er verhindert jede Selektion.","Er führt neue adaptive Variation zu.","Er eliminiert Mutation.","Er erzeugt immer Artenbildung."]'::jsonb,'1'::jsonb,'Genfluss kann sowohl maladaptive als auch adaptive Allele und zusätzliche Variation einbringen.',2,3,true),
('lecture-local-adaptation','short_answer','Entwerfen Sie ein minimales Experiment, das genetische Differenzierung, Plastizität und lokale Anpassung zwischen zwei Populationen entlang eines Feuchtegradienten trennt.',null,null,'Erwartet wird ein Common Garden oder reziprokes Transplantationsdesign mit beiden Herkünften in beiden Umwelten, Replikation und Fitnessmessung.',4,4,true),
-- climate
('lecture-climate-biomes','multiple_choice','Warum sind viele Gebiete um 30° Breite trocken?','["Dort fehlt Solarstrahlung.","Feuchte Luft steigt dauerhaft auf.","Absinkende Luft subtropischer Hochdruckgürtel erwärmt und trocknet sich.","Die Erdachse ist dort stärker geneigt."]'::jsonb,'2'::jsonb,'Absinkende Luft hemmt Kondensation und Niederschlag.',2,1,true),
('lecture-climate-biomes','true_false','Ein extremes Hochwasserereignis allein definiert das Klima einer Region.','[true,false]'::jsonb,'false'::jsonb,'Klima basiert auf langfristigen statistischen Mustern, nicht auf einem Einzelereignis.',1,2,true),
('lecture-climate-biomes','multiple_choice','Welche Seite eines Gebirges ist typischerweise niederschlagsreicher?','["Lee, weil Luft dort aufsteigt","Luv, weil Luft aufsteigt und abkühlt","Beide immer gleich","Nur die Nordseite"]'::jsonb,'1'::jsonb,'Im Luv steigt Luft auf, kühlt ab und erreicht leichter Kondensation.',2,3,true),
('lecture-climate-biomes','short_answer','Erklären Sie, warum zwei Standorte auf demselben Breitengrad unterschiedliche Biome tragen können. Integrieren Sie mindestens drei Mechanismen.',null,null,'Mögliche Mechanismen sind Ozeanströmungen, Kontinentalität, Relief/Regenschatten, Saisonalität, Boden und Störung.',4,4,true),
-- ecophysiology
('lecture-ecophysiology','multiple_choice','Welcher Zielkonflikt ist direkt mit Stomata verbunden?','["CO2-Aufnahme gegen Wasserverlust","Stickstoffaufnahme gegen Salzabgabe","Wurzelwachstum gegen Samenverbreitung","pH gegen Erdrotation"]'::jsonb,'0'::jsonb,'Stomata ermöglichen CO2-Aufnahme, erhöhen aber die Transpiration.',2,1,true),
('lecture-ecophysiology','true_false','Eine reversible physiologische Reaktion eines Individuums auf Temperatur ist bereits evolutionäre Adaptation.','[true,false]'::jsonb,'false'::jsonb,'Das ist Akklimatisation; Adaptation erfordert erbliche Fitnessunterschiede über Generationen.',1,2,true),
('lecture-ecophysiology','multiple_choice','Welches Experiment trennt Genetik und Umwelt am direktesten?','["Nur Freilandbeobachtung","Common Garden mit mehreren Herkünften und Behandlungen","Messung einer einzelnen Pflanze","Vergleich zweier Fotos"]'::jsonb,'1'::jsonb,'Ein faktorieller Common Garden trennt Herkunft, Umwelt und Interaktion.',2,3,true),
('lecture-ecophysiology','short_answer','Zwei Herkünfte reagieren unterschiedlich auf Trockenheit. Formulieren Sie, wie Sie Plastizität, genetische Differenzierung und lokale Anpassung statistisch und biologisch unterscheiden.',null,null,'Erwartet werden Umwelt-, Herkunfts- und Herkunft×Umwelt-Effekt sowie Fitnessbezug und Heimvorteil.',4,4,true);

commit;
